### ISSUE TITLE
Create a firebase project

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/charge-hub#2]
We'll need to create a firebase project with two websites. (One for live and one for development).

We'll also need a firestore database to store charge locations in.

Once it's created we should make sure we update the readme with the new information.

**Comment by michaelfitzhavey** [comment]
Once created don't forget to invite me `michael.fitzhavey@gmail.com`

**Comment by maxcramer** [comment]
Yes i agree, invite me info@maxcramer101.com

**Comment by michaelfitzhavey** [comment]
The project has been created: `charge-hub`
