### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/charge-hub#28]
We should have consistent branding across our logos and images. Some places I can think:

- pin icon for users current location
- pin icon for charge points
- favicon
- logo?
- colour scheme?

**Comment by maxcramer** [comment]
## New Logo Idea

![LOGO V3 DARK GREEN](https://user-images.githubusercontent.com/39188094/105757628-1b948600-5f46-11eb-9345-d80b239d2a8b.png)

`<div style={{backgroundColor: 'black'}}>![LOGO V3 WHITE](https://user-images.githubusercontent.com/39188094/105757631-1c2d1c80-5f46-11eb-8733-17945e217f11.png)</div>`

**Comment by maxcramer** [comment]
# Custom Pins 

## Menu Icon: Add Location
![ADD Charge Location Pin](https://user-images.githubusercontent.com/39188094/105848479-eedc7f00-5fd6-11eb-870c-db4a714fee91.png)

## Map Icon: Charge Location
![Charge Location Pin](https://user-images.githubusercontent.com/39188094/105848484-f00dac00-5fd6-11eb-96fe-f9a4464c6601.png)

## Map Icon: My Location
![My Location Pin](https://user-images.githubusercontent.com/39188094/105848486-f00dac00-5fd6-11eb-8236-83b4e533a1ac.png)

**Comment by michaelfitzhavey** [comment]
@maxcramer Icons are good but we could use them in multiple colours for an active / inactive state. Also lets make sure we have these source files in case we need to make minor tweaks down the line

**Comment by michaelfitzhavey** [comment]
closed as referenced in #35
