### ISSUE TITLE
Improvements: Add Location User Journey 

### ISSUE THREAD

**Issue by maxcramer** [holistic-web/charge-hub#31]
## After a user selects to add a new locations

- [ ] Stop map from reloading on key down on add location page - CLAIMED -Dan #32 (draft)

-  [x] Select on the map (taking up 80% of space) with location search bar underneath (should take current location as initial load for this map

-  [ ] Takes through to info page that takes name and other required data

-  [x] This is then submitted to the database and adds to the map list

**Comment by michaelfitzhavey** [comment]
closing and work is complete on development
